# Run docker-compose up

version: '3'

services:
  nginx_demo:
    image: nginx:1.13.7-alpine
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./src/app/nginx/Dockerfile
    volumes:
      - ./src/app/website:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - flask_api
    links:
      - flask_api

  flask_api:
    container_name: flask_api
    restart: always
    build:
      context: .
      dockerfile: ./src/app/flask/Dockerfile
    volumes:
      - ./src/app/flask:/usr/src/app
    ports:
      - "5000:5000"